// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ5KwPtcH8OlVN7cSHvLKDJQE8SRBwj3U',
    appId: '1:167612364118:web:e5c7c7b1a9f5aa09ac92f7',
    messagingSenderId: '167612364118',
    projectId: 'myband-42825',
    authDomain: 'myband-42825.firebaseapp.com',
    storageBucket: 'myband-42825.firebasestorage.app',
    measurementId: 'G-GRDB2Q223Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJZlBoCR7oJDRuMQfRb930o8cYFrqHy-k',
    appId: '1:167612364118:android:941c2e09f5a5cb9dac92f7',
    messagingSenderId: '167612364118',
    projectId: 'myband-42825',
    storageBucket: 'myband-42825.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDabLmS4MZoA0dXF-FJgJf0noYKkQQx04',
    appId: '1:167612364118:ios:c13e9076a4611bc7ac92f7',
    messagingSenderId: '167612364118',
    projectId: 'myband-42825',
    storageBucket: 'myband-42825.firebasestorage.app',
    iosBundleId: 'com.example.myBand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDabLmS4MZoA0dXF-FJgJf0noYKkQQx04',
    appId: '1:167612364118:ios:c13e9076a4611bc7ac92f7',
    messagingSenderId: '167612364118',
    projectId: 'myband-42825',
    storageBucket: 'myband-42825.firebasestorage.app',
    iosBundleId: 'com.example.myBand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ5KwPtcH8OlVN7cSHvLKDJQE8SRBwj3U',
    appId: '1:167612364118:web:58643d0dd10a1963ac92f7',
    messagingSenderId: '167612364118',
    projectId: 'myband-42825',
    authDomain: 'myband-42825.firebaseapp.com',
    storageBucket: 'myband-42825.firebasestorage.app',
    measurementId: 'G-Q8DB6YKFHH',
  );

}